version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:latest
    resource_class: medium # ここでスペック指定

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install   # npmパッケージインストール
      - run: npm run build  # ソースビルド実行
      - persist_to_workspace:
          root: .
          paths: [ '*' ]

  deploy_prod:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    resource_class: medium
    steps:
      - attach_workspace: 
          at: .
      - aws-s3/sync: 
          from: ./build
          to: $BUCKET_URL
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIS_PRD --path "/*"
      
  deploy_dev:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    resource_class: medium
    steps:
      - attach_workspace: 
          at: .
      - aws-s3/sync: 
          from: ./build
          to: $BUCKET_URL
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIS_DEV --path "/*"
      
workflows:
  version: 2
  s3-deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only: main

      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only: develop